### PR TITLE
Proxy PAC URL command line option

### PR DESCRIPTION
**Pull request by JalfResi**
Added missing Proxy PAC URL command line option

### CODE REVIEW

**Comment by kenshaw** [comment]
Please change the name of this flag to ProxyPacURL and rebase into one commit.

**Comment by JalfResi** [comment]
Apologies for the multiple stabs at this - messed up my rebase!

**Comment by kenshaw** [comment]
I merged this, but messed up the rebase, crushing the commit history. Sorry. I just noticed that you used `*url.URL` instead of just a string as the parameter. Is there any reason for this?

**Comment by JalfResi** [comment]
Yeah the proxy-PAC-url command line option should be a URL to a PAC file. Made sense to ensure valid urls were being passed to it.

Thanks for merging!

**Pull request closed without merging**
